[package]
name = "trisult-derive"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sharp0802/trisult"

categories = ["no-std::no-alloc", "rust-patterns"]
keywords = ["error-handling", "diagnostics", "result", "validation", "derive"]

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full"] }
