[package]
name = "trisult"
version = "0.4.0"
edition = "2024"
rust-version = "1.85.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sharp0802/trisult"

categories = ["no-std", "no-std::no-alloc", "rust-patterns"]
keywords = ["error-handling", "diagnostics", "result", "validation"]
readme = "README.md"
description = "An accumulating alternative to standard `Result<T, E>`."

[lib]
# Disable libtest
bench = false

[features]
default = ["alloc"]
alloc = ["dep:smallvec", "trisult-macros/alloc"]

[dependencies]
smallvec = { version = "2.0.0-alpha.12", optional = true }
trisult-macros = { path = "../macros", version = "0.4" }

[dev-dependencies]
thiserror = "2.0"
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
