[package]
name = "trisult"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sharp0802/trisult"

categories = ["no-std::no-alloc", "rust-patterns"]
keywords = ["error-handling", "diagnostics", "result", "validation"]
readme = "../README.md"
description = "An accumulating alternative to standard `Result<T, E>`."

[features]
alloc = ["dep:smallvec"]

[dependencies]
smallvec = { version = "2.0.0-alpha.12", optional = true }
trisult-derive = { path = "../derive", version = "0.1" }

[dev-dependencies]
trisult = { path = ".", features = ["alloc"] }
thiserror = "2.0"
